/*
  As insígnias passam de três níveis para as sete classes dos Desbravadores.

  Eram bronze, prata e ouro — a escala de medalha de pódio, que não diz nada
  sobre o percurso de quem estuda e não tem degrau nenhum entre "comecei" e
  "terminei". Agora são Amigo, Companheiro, Pesquisador, Pioneiro,
  Excursionista, Guia e Líder, que é a escala que o clube já sabe ordenar de
  cor, e toda família de conquista vai de ponta a ponta dela.

  ── A ordem aqui importa, e é por isso que ela é esta ────────────────────
  A restrição velha só aceita os três nomes antigos, e a nova só aceita os
  sete. Trocar a restrição antes de traduzir as linhas faria o ALTER recusar a
  tabela inteira — há 79 linhas gravadas em bronze, prata e ouro. Então:
  derruba-se a restrição, traduz-se o que existe, semeia-se o catálogo novo, e
  só então a restrição volta, já com tudo dentro dela.

  ── Nenhum código antigo foi aposentado ─────────────────────────────────
  As escadas foram montadas **em volta** dos limiares que já existiam: 5, 10,
  25 e 50 lições continuam sendo 5, 10, 25 e 50, com os mesmos códigos e os
  mesmos nomes. Os 36 degraus herdados são UPDATE; os 55 novos e as de
  identidade são INSERT. Ninguém perde insígnia, e ninguém vê uma que tinha
  mudar de nome.

  DO UPDATE, e não DO NOTHING: o `tier` de todas mudou, e o nome de várias
  também. DO NOTHING deixaria o banco com a redação velha para sempre — é a
  mesma decisão do catálogo original.
*/

-- ─── 1. A restrição velha sai da frente ───────────────────────────────────
ALTER TABLE badges DROP CONSTRAINT IF EXISTS badges_tier_check;

-- ─── 2. O que já está gravado é traduzido ─────────────────────────────────
/*
  Inclusive as linhas que o catálogo novo não cita — `mini_html` e
  `lab_image_lab`, que são a vereda de HTML e o laboratório de imagens com os
  nomes de antes de serem renomeados e divididos. Elas continuam no banco de
  propósito: quem as conquistou continua tendo, e uma decisão nossa não se
  cobra de quem já andou. Sem esta tradução, a restrição do passo 4 recusaria
  justamente essas duas.

  O destino de cada tier é a classe onde a maior parte daquele grupo de fato
  aterrissou, e é o mesmo mapa que o frontend usa durante a janela em que os
  dois workflows correm em paralelo.
*/
UPDATE badges SET tier = CASE tier
  WHEN 'bronze' THEN 'companheiro'
  WHEN 'silver' THEN 'pioneiro'
  WHEN 'gold'   THEN 'excursionista'
  ELSE tier
END
WHERE tier IN ('bronze', 'silver', 'gold');

ALTER TABLE badges ALTER COLUMN tier SET DEFAULT 'amigo';

-- ─── 3. O catálogo inteiro, 132 insígnias ──────────────────────────────────
INSERT INTO badges (code, name, description, icon, tier, sort_order) VALUES
  ('first_step', 'Primeiro Passo',
   'Cumpriu o primeiro requisito de uma trilha.',
   'footprints', 'amigo', 1),
  ('requisitos_10', 'Dez Requisitos',
   'Cumpriu dez requisitos oficiais.',
   'footprints', 'companheiro', 2),
  ('requisitos_25', 'Vinte e Cinco Requisitos',
   'Cumpriu vinte e cinco requisitos oficiais.',
   'footprints', 'pesquisador', 3),
  ('requisitos_50', 'Cinquenta Requisitos',
   'Cumpriu cinquenta requisitos oficiais.',
   'footprints', 'pioneiro', 4),
  ('requisitos_100', 'Cem Requisitos',
   'Cumpriu cem requisitos oficiais.',
   'footprints', 'excursionista', 5),
  ('requisitos_145', 'Cento e quarenta e cinco Requisitos',
   'Cumpriu cento e quarenta e cinco requisitos oficiais.',
   'footprints', 'guia', 6),
  ('requisitos_192', 'Cento e noventa e dois Requisitos',
   'Cumpriu cento e noventa e dois requisitos oficiais.',
   'footprints', 'lider', 7),
  ('primeira_licao', 'Primeira Lição',
   'Concluiu a primeira lição.',
   'theory', 'amigo', 8),
  ('licoes_5', 'Cinco Lições',
   'Concluiu cinco lições.',
   'theory', 'companheiro', 9),
  ('licoes_10', 'Dez Lições',
   'Concluiu dez lições.',
   'theory', 'pesquisador', 10),
  ('licoes_25', 'Vinte e Cinco Lições',
   'Concluiu vinte e cinco lições.',
   'theory', 'pioneiro', 11),
  ('licoes_50', 'Cinquenta Lições',
   'Concluiu cinquenta lições.',
   'theory', 'excursionista', 12),
  ('licoes_75', 'Setenta e cinco Lições',
   'Concluiu setenta e cinco lições.',
   'theory', 'guia', 13),
  ('licoes_110', 'Cento e dez Lições',
   'Concluiu cento e dez lições.',
   'theory', 'lider', 14),
  ('module_complete', 'Módulo Concluído',
   'Concluiu todos os requisitos de um módulo.',
   'layers', 'amigo', 15),
  ('modulos_3', 'Três Módulos',
   'Concluiu três módulos por inteiro.',
   'layers', 'companheiro', 16),
  ('modulos_5', 'Cinco Módulos',
   'Concluiu cinco módulos.',
   'layers', 'pesquisador', 17),
  ('modulos_10', 'Dez Módulos',
   'Concluiu dez módulos por inteiro.',
   'layers', 'pioneiro', 18),
  ('modulos_15', 'Quinze Módulos',
   'Concluiu quinze módulos.',
   'layers', 'excursionista', 19),
  ('modulos_28', 'Vinte e oito Módulos',
   'Concluiu vinte e oito módulos por inteiro.',
   'layers', 'guia', 20),
  ('modulos_45', 'Quarenta e cinco Módulos',
   'Concluiu quarenta e cinco módulos por inteiro.',
   'layers', 'lider', 21),
  ('primeiro_laboratorio', 'Primeiro Laboratório',
   'Concluiu o primeiro laboratório.',
   'lab', 'amigo', 22),
  ('laboratorios_3', 'Três Laboratórios',
   'Venceu três laboratórios diferentes.',
   'lab', 'companheiro', 23),
  ('laboratorios_6', 'Seis Laboratórios',
   'Venceu seis laboratórios diferentes.',
   'lab', 'pesquisador', 24),
  ('laboratorios_10', 'Dez Laboratórios',
   'Venceu dez laboratórios diferentes.',
   'lab', 'pioneiro', 25),
  ('laboratorios_15', 'Quinze Laboratórios',
   'Venceu quinze laboratórios diferentes.',
   'lab', 'excursionista', 26),
  ('laboratorios_21', 'Vinte e uma Laboratórios',
   'Venceu vinte e uma laboratórios diferentes.',
   'lab', 'guia', 27),
  ('laboratorios_28', 'Vinte e oito Laboratórios',
   'Venceu vinte e oito laboratórios diferentes.',
   'lab', 'lider', 28),
  ('streak_3', 'Sequência de 3 Dias',
   'Praticou a trilha 3 dias seguidos.',
   'flame', 'amigo', 29),
  ('streak_7', 'Sequência de 7 Dias',
   'Praticou a trilha 7 dias seguidos.',
   'flame', 'companheiro', 30),
  ('streak_14', 'Sequência de 14 Dias',
   'Praticou a trilha 14 dias seguidos.',
   'flame', 'pesquisador', 31),
  ('streak_30', 'Sequência de 30 Dias',
   'Praticou a trilha 30 dias seguidos.',
   'flame', 'pioneiro', 32),
  ('ofensiva_60', 'Sequência de 60 Dias',
   'Venceu alguma coisa sessenta dias seguidos.',
   'flame', 'excursionista', 33),
  ('ofensiva_120', 'Sequência de 120 Dias',
   'Venceu alguma coisa cento e vinte dias seguidos.',
   'flame', 'guia', 34),
  ('ofensiva_250', 'Sequência de 250 Dias',
   'Venceu alguma coisa duzentos e cinquenta dias seguidos.',
   'flame', 'lider', 35),
  ('dias_5', 'Cinco Dias de Estudo',
   'Estudou em cinco dias diferentes.',
   'calendar', 'amigo', 36),
  ('dias_15', 'Quinze Dias de Estudo',
   'Estudou em quinze dias diferentes.',
   'calendar', 'companheiro', 37),
  ('dias_30', 'Trinta Dias de Estudo',
   'Estudou em trinta dias diferentes.',
   'calendar', 'pesquisador', 38),
  ('constancia_60', 'Sessenta Dias de Estudo',
   'Estudou em sessenta dias diferentes.',
   'calendar', 'pioneiro', 39),
  ('constancia_120', 'Cento e vinte Dias de Estudo',
   'Estudou em cento e vinte dias diferentes.',
   'calendar', 'excursionista', 40),
  ('constancia_210', 'Duzentos e dez Dias de Estudo',
   'Estudou em duzentos e dez dias diferentes.',
   'calendar', 'guia', 41),
  ('constancia_365', 'Trezentos e sessenta e cinco Dias de Estudo',
   'Estudou em trezentos e sessenta e cinco dias diferentes.',
   'calendar', 'lider', 42),
  ('licao_perfeita', 'Lição sem Erro',
   'Acertou todas as questões de uma lição.',
   'star', 'amigo', 43),
  ('semerro_5', 'Cinco Lições sem Erro',
   'Acertou tudo em cinco lições.',
   'star', 'companheiro', 44),
  ('licoes_perfeitas_10', 'Dez Lições sem Erro',
   'Acertou tudo em dez lições.',
   'star', 'pesquisador', 45),
  ('licoes_perfeitas_25', 'Vinte e Cinco Lições sem Erro',
   'Acertou tudo em vinte e cinco lições.',
   'star', 'pioneiro', 46),
  ('semerro_45', 'Quarenta e cinco Lições sem Erro',
   'Acertou tudo em quarenta e cinco lições.',
   'star', 'excursionista', 47),
  ('semerro_65', 'Sessenta e cinco Lições sem Erro',
   'Acertou tudo em sessenta e cinco lições.',
   'star', 'guia', 48),
  ('semerro_90', 'Noventa Lições sem Erro',
   'Acertou tudo em noventa lições.',
   'star', 'lider', 49),
  ('primeira_prova', 'Primeira Avaliação',
   'Concluiu a primeira avaliação final.',
   'exam', 'amigo', 50),
  ('avaliacoes_2', 'Duas Avaliações',
   'Concluiu duas avaliações finals.',
   'exam', 'companheiro', 51),
  ('avaliacoes_3', 'Três Avaliações',
   'Concluiu três avaliações finals.',
   'exam', 'pesquisador', 52),
  ('avaliacoes_5', 'Cinco Avaliações',
   'Concluiu cinco avaliações finals.',
   'exam', 'pioneiro', 53),
  ('avaliacoes_7', 'Sete Avaliações',
   'Concluiu sete avaliações finals.',
   'exam', 'excursionista', 54),
  ('avaliacoes_10', 'Dez Avaliações',
   'Concluiu dez avaliações finals.',
   'exam', 'guia', 55),
  ('avaliacoes_13', 'Treze Avaliações',
   'Concluiu treze avaliações finals.',
   'exam', 'lider', 56),
  ('perfect_exam', 'Nota Máxima',
   'Acertou 100% em uma avaliação final.',
   'bullseye', 'amigo', 57),
  ('provas_perfeitas_2', 'Duas Notas Máximas',
   'Acertou 100% em duas avaliações finais.',
   'bullseye', 'companheiro', 58),
  ('notamaxima_3', 'Três Notas Máximas',
   'Acertou 100% em três avaliações finals.',
   'bullseye', 'pesquisador', 59),
  ('notamaxima_4', 'Quatro Notas Máximas',
   'Acertou 100% em quatro avaliações finals.',
   'bullseye', 'pioneiro', 60),
  ('notamaxima_6', 'Seis Notas Máximas',
   'Acertou 100% em seis avaliações finals.',
   'bullseye', 'excursionista', 61),
  ('notamaxima_9', '9 Notas Máximas',
   'Acertou 100% em 9 avaliações finals.',
   'bullseye', 'guia', 62),
  ('notamaxima_13', 'Treze Notas Máximas',
   'Acertou 100% em treze avaliações finals.',
   'bullseye', 'lider', 63),
  ('trilhas_1', 'Uma Trilha',
   'Concluiu uma especialidade.',
   'trophy', 'amigo', 64),
  ('duas_trilhas', 'Duas Trilhas',
   'Concluiu duas especialidades.',
   'trophy', 'companheiro', 65),
  ('tres_trilhas', 'Três Trilhas',
   'Concluiu três especialidades.',
   'trophy', 'pesquisador', 66),
  ('cinco_trilhas', 'Cinco Trilhas',
   'Concluiu cinco especialidades.',
   'trophy', 'pioneiro', 67),
  ('trilhas_7', 'Sete Trilhas',
   'Concluiu sete especialidades.',
   'trophy', 'excursionista', 68),
  ('trilhas_10', 'Dez Trilhas',
   'Concluiu dez especialidades.',
   'trophy', 'guia', 69),
  ('trilhas_13', 'Treze Trilhas',
   'Concluiu treze especialidades.',
   'trophy', 'lider', 70),
  ('veredas_1', 'Uma Vereda',
   'Percorreu uma vereda até o fim.',
   'route', 'amigo', 71),
  ('veredas_2', 'Duas Veredas',
   'Percorreu duas veredas até o fim.',
   'route', 'companheiro', 72),
  ('veredas_4', 'Quatro Veredas',
   'Percorreu quatro veredas até o fim.',
   'route', 'pesquisador', 73),
  ('veredas_8', 'Oito Veredas',
   'Percorreu oito veredas até o fim.',
   'route', 'pioneiro', 74),
  ('veredas_15', 'Quinze Veredas',
   'Percorreu quinze veredas até o fim.',
   'route', 'excursionista', 75),
  ('veredas_30', 'Trinta Veredas',
   'Percorreu trinta veredas até o fim.',
   'route', 'guia', 76),
  ('veredas_51', 'Cinquenta e uma Veredas',
   'Percorreu cinquenta e uma veredas até o fim.',
   'route', 'lider', 77),
  ('primeiro_token', 'Primeiro Token.Web()',
   'Recebeu o primeiro certificado.',
   'award', 'amigo', 78),
  ('tokens_2', 'Dois Token.Web()',
   'Recebeu dois certificados.',
   'award', 'companheiro', 79),
  ('tokens_3', 'Três Token.Web()',
   'Recebeu três certificados.',
   'award', 'pesquisador', 80),
  ('tokens_5', 'Cinco Token.Web()',
   'Recebeu cinco certificados.',
   'award', 'pioneiro', 81),
  ('tokens_10', 'Dez Token.Web()',
   'Recebeu dez certificados.',
   'award', 'excursionista', 82),
  ('tokens_20', 'Vinte Token.Web()',
   'Recebeu vinte certificados.',
   'award', 'guia', 83),
  ('tokens_40', 'Quarenta Token.Web()',
   'Recebeu quarenta certificados.',
   'award', 'lider', 84),
  ('xp_100', 'Cem de XP',
   'Somou cem pontos de experiência.',
   'zap', 'amigo', 85),
  ('xp_300', '300 de XP',
   'Somou 300 pontos de experiência.',
   'zap', 'companheiro', 86),
  ('xp_500', 'Quinhentos de XP',
   'Somou quinhentos pontos de experiência.',
   'zap', 'pesquisador', 87),
  ('xp_1000', 'Mil de XP',
   'Somou mil pontos de experiência.',
   'zap', 'pioneiro', 88),
  ('xp_2500', '2500 de XP',
   'Somou 2500 pontos de experiência.',
   'zap', 'excursionista', 89),
  ('xp_6000', '6000 de XP',
   'Somou 6000 pontos de experiência.',
   'zap', 'guia', 90),
  ('xp_12000', '12000 de XP',
   'Somou 12000 pontos de experiência.',
   'zap', 'lider', 91),
  ('coruja', 'Coruja',
   'Estudou entre a meia-noite e as cinco da manhã.',
   'clock', 'companheiro', 92),
  ('madrugador', 'Madrugador',
   'Estudou antes das sete da manhã.',
   'clock', 'companheiro', 93),
  ('fim_de_semana', 'Fim de Semana',
   'Estudou num sábado ou domingo.',
   'calendar', 'companheiro', 94),
  ('semana_inteira', 'Semana Inteira',
   'Estudou em todos os sete dias da semana, em algum momento.',
   'calendar', 'companheiro', 95),
  ('lab_web_lab', 'Navegação com cuidado',
   'Concluiu o laboratório de navegar e pesquisar.',
   'lab', 'companheiro', 96),
  ('lab_mail_lab', 'Correio em ordem',
   'Concluiu o laboratório de e-mail e golpes.',
   'lab', 'companheiro', 97),
  ('lab_threat_lab', 'Caça-ameaças',
   'Concluiu o laboratório de ameaças e proteção.',
   'lab', 'companheiro', 98),
  ('lab_pact_builder', 'Compromisso assinado',
   'Escreveu o próprio compromisso de uso da internet.',
   'lab', 'companheiro', 99),
  ('lab_filipenses', 'Filtro de Filipenses',
   'Concluiu o estudo de Filipenses 4:8.',
   'lab', 'companheiro', 100),
  ('lab_text_editor', 'Primeiro relatório',
   'Escreveu e entregou um texto de trilha.',
   'lab', 'amigo', 101),
  ('lab_redacao_guiada', 'Relatório construído',
   'Montou um relatório pesquisando etapa por etapa.',
   'lab', 'companheiro', 102),
  ('lab_code_lab', 'Página escrita à mão',
   'Concluiu o laboratório de HTML.',
   'lab', 'pioneiro', 103),
  ('lab_table_challenge', 'Dados em linhas e colunas',
   'Montou uma página com tabela.',
   'lab', 'pioneiro', 104),
  ('lab_image_compress', 'Imagens leves',
   'Espremeu uma foto até caber em 15 KB sem deixar de ser vista.',
   'lab', 'pioneiro', 105),
  ('lab_image_create', 'Estúdio do clube',
   'Desenhou o logo, os botões e o header do site.',
   'lab', 'pioneiro', 106),
  ('lab_site_lab', 'Site de quatro páginas',
   'Montou um site completo e navegável.',
   'lab', 'pioneiro', 107),
  ('lab_ai_lab', 'Pedido bem feito',
   'Concluiu o laboratório de produção com IA.',
   'lab', 'pioneiro', 108),
  ('lab_computer_care', 'Máquina cuidada',
   'Concluiu o laboratório de cuidados com o computador.',
   'lab', 'companheiro', 109),
  ('lab_file_manager', 'Pastas em ordem',
   'Concluiu o laboratório de pastas e arquivos.',
   'lab', 'companheiro', 110),
  ('lab_formatacao_texto', 'Documento apresentável',
   'Formatou um documento inteiro, da folha às listas.',
   'lab', 'companheiro', 111),
  ('lab_operacoes_arquivo', 'Tarefas do dia',
   'Compactou, exportou em pdf, instalou e imprimiu.',
   'lab', 'companheiro', 112),
  ('lab_insercao_texto', 'Documento montado',
   'Inseriu tabela, imagem, cabeçalho e numeração num documento.',
   'lab', 'pesquisador', 113),
  ('lab_planilha', 'Planilha que calcula',
   'Montou uma planilha com alinhamento, mesclagem e fórmulas.',
   'lab', 'pesquisador', 114),
  ('lab_area_de_trabalho', 'Dono da máquina',
   'Consultou, ajustou e capturou o que o sistema mostra.',
   'lab', 'pesquisador', 115),
  ('lab_estilos_texto', 'Documento que se monta sozinho',
   'Aplicou estilos e deixou o sumário se montar a partir deles.',
   'lab', 'pesquisador', 116),
  ('lab_planilha_avancada', 'Planilha que responde',
   'Filtrou, congelou o cabeçalho e desenhou o gráfico certo.',
   'lab', 'pesquisador', 117),
  ('lab_banco_de_dados', 'Agenda com estrutura',
   'Montou um banco de dados com vinte e cinco fichas.',
   'lab', 'pesquisador', 118),
  ('lab_apresentacao', 'Apresentação pronta',
   'Montou uma apresentação com modelo, mídia e PDF.',
   'lab', 'pesquisador', 119),
  ('lab_correio_completo', 'Correio do clube',
   'Escreveu, anexou, arquivou, respondeu e encaminhou.',
   'lab', 'pesquisador', 120),
  ('lab_configuracoes_sistema', 'Máquina ajustada',
   'Limpou o disco, escolheu os programas padrão e criou um usuário.',
   'lab', 'pesquisador', 121),
  ('ap034_complete', 'Trilha AP034 Internet',
   'Concluiu todos os requisitos da especialidade AP034 Internet.',
   'trophy', 'pesquisador', 122),
  ('ap035_complete', 'Trilha AP035 Internet, Avançado',
   'Concluiu todos os requisitos da especialidade AP035 Internet, Avançado.',
   'trophy', 'lider', 123),
  ('ap041_complete', 'Trilha AP041 Computação 1',
   'Concluiu todos os requisitos da especialidade AP041 Computação 1.',
   'trophy', 'pesquisador', 124),
  ('ap042_complete', 'Trilha AP042 Computação 2',
   'Concluiu todos os requisitos da especialidade AP042 Computação 2.',
   'trophy', 'pesquisador', 125),
  ('ap043_complete', 'Trilha AP043 Computação 3',
   'Concluiu todos os requisitos da especialidade AP043 Computação 3.',
   'trophy', 'excursionista', 126),
  ('ap044_complete', 'Trilha AP044 Computação 4',
   'Concluiu todos os requisitos da especialidade AP044 Computação 4.',
   'trophy', 'excursionista', 127),
  ('vereda_cc001', 'Vereda CC001 Lógica com Scratch',
   'Percorreu a vereda CC001 Lógica com Scratch até o fim.',
   'route', 'excursionista', 128),
  ('vereda_cc002', 'Vereda CC002 Python',
   'Percorreu a vereda CC002 Python até o fim.',
   'route', 'excursionista', 129),
  ('vereda_cc003', 'Vereda CC003 Terminal e Git',
   'Percorreu a vereda CC003 Terminal e Git até o fim.',
   'route', 'pioneiro', 130),
  ('vereda_html', 'Vereda CC-FE001 HTML',
   'Percorreu a vereda CC-FE001 HTML até o fim.',
   'route', 'excursionista', 131),
  ('vereda_css', 'Vereda CC-FE002 CSS',
   'Percorreu a vereda CC-FE002 CSS até o fim.',
   'route', 'excursionista', 132)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  icon = EXCLUDED.icon,
  tier = EXCLUDED.tier,
  sort_order = EXCLUDED.sort_order;

-- ─── 4. E a restrição volta, com as sete ──────────────────────────────────
ALTER TABLE badges ADD CONSTRAINT badges_tier_check
  CHECK (tier IN ('amigo', 'companheiro', 'pesquisador', 'pioneiro',
                  'excursionista', 'guia', 'lider'));
